name: daily-highscore

on:
  workflow_dispatch:
  schedule:
    # Täglich um 06:30 Uhr (UTC) -> in DE im Sommer 08:30, im Winter 07:30
    - cron: "30 6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          MG_HIGHSCORE_URL: ${{ secrets.MG_HIGHSCORE_URL }}
          MG_WATCHLIST:     ${{ secrets.MG_WATCHLIST }}
          MG_SESSIONID:     ${{ secrets.MG_SESSIONID }}
          MG_CSRFTOKEN:     ${{ secrets.MG_CSRFTOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scraper.py
