name: daily-highscore

on:
  schedule:
    - cron: "59 22 * * *"   # 23:59 CET
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          MG_USERNAME: ${{ secrets.MG_USERNAME }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MG_CONNECT_ID: ${{ secrets.MG_CONNECT_ID }}
          MG_COOKIE: ${{ secrets.MG_COOKIE }}
        run: |
          python scraper.py || echo "script_returned_error"

      - name: Commit debug and state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/state.json || true
          git add data/last_highscore.html || true
          git commit -m "Update state and debug" || echo "nichts zu committen"
          git push || true
