name: daily-highscore

on:
  schedule:
    - cron: "0 20 * * *"  # jeden Tag um 20:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        env:
          MG_HIGHSCORE_URL: ${{ secrets.MG_HIGHSCORE_URL }}
          MG_WATCHLIST: ${{ secrets.MG_WATCHLIST }}
          MG_SESSIONID: ${{ secrets.MG_SESSIONID }}
          MG_USERNAME: ${{ secrets.MG_USERNAME }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          MG_CSRFTOKEN: ${{ secrets.MG_CSRFTOKEN }}
          MG_CONNECT_ID: ${{ secrets.MG_CONNECT_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python scraper.py
