name: run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"   # täglich 07:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MG_USERNAME:     ${{ secrets.MG_USERNAME }}
          MG_PASSWORD:     ${{ secrets.MG_PASSWORD }}
          MG_SESSIONID:    ${{ secrets.MG_SESSIONID }}     # optional
          MG_PHPSESSID:    ${{ secrets.MG_PHPSESSID }}     # optional
          MG_COOKIE:       ${{ secrets.MG_COOKIE }}        # optional (Alias PHPSESSID)
          MG_CSRFTOKEN:    ${{ secrets.MG_CSRFTOKEN }}     # optional
          MG_CONNECT_ID:   ${{ secrets.MG_CONNECT_ID }}    # optional (Default 240)
          MG_WATCHLIST:    ${{ secrets.MG_WATCHLIST }}     # optional, wenn keine players.txt
          MG_DEBUG:        ${{ secrets.MG_DEBUG }}         # optional, "1" für Debug
        run: |
          python scraper.py
