name: daily-highscore

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"  # täglich 06:30 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          MG_HIGHSCORE_URL: ${{ secrets.MG_HIGHSCORE_URL }}
          MG_SESSIONID:     ${{ secrets.MG_SESSIONID }}
          MG_CSRFTOKEN:     ${{ secrets.MG_CSRFTOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # MG_WATCHLIST ist optional – wird nur genutzt, falls KEINE players.txt vorhanden ist
        run: python scraper.py
