name: daily-highscore

on:
  workflow_dispatch:
  schedule:
    - cron: "6 4 * * *"   # täglich 04:06 UTC (anpassen, wenn du willst)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        env:
          MG_HIGHSCORE_URL: ${{ secrets.MG_HIGHSCORE_URL }}
          MG_SESSIONID:     ${{ secrets.MG_SESSIONID }}
          MG_CSRFTOKEN:     ${{ secrets.MG_CSRFTOKEN }}
          DISCORD_WEBHOOK:  ${{ secrets.DISCORD_WEBHOOK }}
          PLAYERS_FILE:     players.txt
        run: |
          python scraper.py
