name: daily-highscore

on:
  # täglicher Lauf (UTC)
  schedule:
    - cron: "13 5 * * *"
  # manuell startbar
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        # >>> HIER werden alle Secrets/ENVs in den Prozess gegeben <<<
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MG_USERNAME:     ${{ secrets.MG_USERNAME }}
          MG_PASSWORD:     ${{ secrets.MG_PASSWORD }}
          MG_COOKIE:       ${{ secrets.MG_COOKIE }}       # optional (int3 PHPSESSID)
          MG_PHPSESSID:    ${{ secrets.MG_PHPSESSID }}    # optional (int3 PHPSESSID)
          MG_SESSIONID:    ${{ secrets.MG_SESSIONID }}    # optional (moonid sessionid)
          MG_CSRFTOKEN:    ${{ secrets.MG_CSRFTOKEN }}    # optional (moonid csrftoken)
          MG_CONNECT_ID:   ${{ secrets.MG_CONNECT_ID }}   # optional (standard 240)
          MG_DEBUG:        ${{ secrets.MG_DEBUG }}        # optional: 1 für Debug-Logs
        run: python scraper.py
