permissions:
  contents: write

jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Run monthly scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MG_USERNAME: ${{ secrets.MG_USERNAME }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          MG_SESSIONID: ${{ secrets.MG_SESSIONID }}
          MG_PHPSESSID: ${{ secrets.MG_PHPSESSID }}
          MG_COOKIE: ${{ secrets.MG_COOKIE }}
          MG_CSRFTOKEN: ${{ secrets.MG_CSRFTOKEN }}
          MG_CONNECT_ID: ${{ secrets.MG_CONNECT_ID }}
        run: python scraper.py

      - name: Commit monthly state
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/state.json || true
          git commit -m "monthly state update" || echo "no changes"
          git push || true
