name: monthly
on:
  schedule:
    # Am 1. des Monats 18:00 UTC. Entspricht 20:00 CEST bzw. 19:00 CET.
    - cron: "0 18 1 * *"
  workflow_dispatch:

jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore monthly state cache
        uses: actions/cache@v4
        with:
          path: data
          key: monthly-state

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run scraper (monthly)
        env:
          MG_USERNAME: ${{ secrets.MG_USERNAME }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MONTHLY }} # optional eigener Kanal
          MG_DEBUG: "0"
        run: python scraper.py

      - name: Save monthly state cache
        uses: actions/cache@v4
        with:
          path: data
          key: monthly-state
          restore-keys: |
            monthly-state
