name: run-weekly

permissions:
  contents: write

on:
  schedule:
    - cron: "0 19 * * 0"
  workflow_dispatch:

jobs:
  run-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          MG_USERNAME: ${{ secrets.MG_USERNAME }}
          MG_PASSWORD: ${{ secrets.MG_PASSWORD }}
          MG_SESSIONID: ${{ secrets.MG_SESSIONID }}
          MG_PHPSESSID: ${{ secrets.MG_PHPSESSID }}
          MG_COOKIE: ${{ secrets.MG_COOKIE }}
          MG_CSRFTOKEN: ${{ secrets.MG_CSRFTOKEN }}
          MG_CONNECT_ID: ${{ secrets.MG_CONNECT_ID }}
        run: |
          python scraper.py

      - name: Mirror weekly state file
        run: |
          mkdir -p data
          if [ -f data/state.json ]; then
            cp data/state.json data/weekly_state.json
          fi

      - name: Commit weekly state
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/state.json data/weekly_state.json || true
          git commit -m "weekly state update" || echo "no changes"
          git push || true
